version: 2.1
orbs: 
  macos: circleci/macos@2.3.1

jobs:
  build:
    macos:
      xcode: "12.5.1"
    steps:
      - checkout
      - run:
          name: "check macOS version"
          command: "sw_vers"

workflows:
  test-build:
    jobs:
      - build