version: 2.1
orbs: 
  macos: circleci/macos@2.3.1

jobs:
  build:
    macos:
      xcode: "12.5.1"
    steps:
      - checkout
      - run:
          name: "xcode version"
          command: "/usr/bin/xcodebuild -version"

workflows:
  say-hello-workflow:
    jobs:
      - build
